version: '3.8'

services:
  webagent:
    build: .
    ports:
      - "8000:8000"  # Prometheus metrics
      - "3000:3000"  # Grafana dashboard
    environment:
      - LLM_MODEL_ID=meta-llama/Llama-3
      - API_KEY=${API_KEY}
      - MCP_ENDPOINT=http://mcp:8080
    volumes:
      - ./logs:/app/logs
    depends_on:
      - prometheus
      - grafana
      - mcp

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin}
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

  mcp:
    image: anthropics/mcp:latest
    ports:
      - "8080:8080"
    environment:
      - MCP_API_KEY=${MCP_API_KEY}
    volumes:
      - mcp_data:/data

volumes:
  prometheus_data:
  grafana_data:
  mcp_data: 